FROM mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04 
ENV ACCEPT_EULA=Y MSSQL_SA_PASSWORD=C0ntrol1* MSSQL_PID=Developer
EXPOSE 1433
CMD CMD ["tail","-f","/dev/null"]


 ## docker build -t sql-examen:latest .

 ## docker container run --name contSqlexamen -p 1433:1433 sql-examen:latest